# Generated by Django 5.2.1 on 2025-06-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialsite',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socialsite',
            name='url_template',
            field=models.URLField(),
        ),
    ]
