# Generated by Django 5.2.1 on 2025-06-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_socialsite_category_alter_socialsite_url_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialsite',
            name='url_template',
            field=models.URLField(unique=True),
        ),
    ]
