# Generated by Django 5.2.1 on 2025-06-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_socialsite_url_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialsite',
            name='category',
            field=models.CharField(default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='socialsite',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
